### ISSUE TITLE
Lua Bit Operations broken

### ISSUE THREAD

**Issue by burningtree** [fuxoft/krypta#2]
Hello,
I trying to re-implement "krypta" in Go language (as a study project, I want to understand Lua & Go more) and I found some serious issue with LuaJIT and its Bit Operations module (Lua BitOp) which this project uses.

It seems that `bit.rshift()` function is broken and sometimes returns incorrect results. I found, for example, this evidence:
```lua
bit.rshift(-1844166528, 8)                -- result = 9573440
```

But that's wrong, correct values are `-7203776`. This is confirmation(s) from other languages:

### Go
https://play.golang.org/p/IqIUgWf4mXZ
```go
package main

import (
	"fmt"
)
func main() {
	fmt.Println(-1844166528 >> 8)   // result = -7203776
}
```

### Rust
https://play.rust-lang.org/?gist=07c4c9519b6ecf77e905f731cabba54a&version=stable
```rust
fn main() {
    println!("{}", -1844166528 >> 8);   // result = -7203776
}
```
### Ruby
```ruby
puts -1844166528 >> 8             # result = -7203776
```
### Javascript
```javascript
console.log(-1844166528 >> 8)     // result = -7203776
```

## Conclusion

I found this problem when I was worked on this piece of code:
https://github.com/fuxoft/krypta/blob/d983f7f4c041e86c4d149a43c62a582998989e08/krypta_luajit.lua#L2647

Its very serious issue - because of that it's not currently possible to create a **compatible** implementation in other language and all secrets/passwords generated till this time are hardly dependent on this broken bitwise library (which have the last release before 3 years on August 2015).

I recommend changing the library for bitwise operations as soon as possible and let everyone know clearly about this change and its consequences.

Anyway, thank you for your work and good luck :)

**Comment by fuxoft** [comment]
Hello and thanks for your interest in Krypta.

Fortunately, this is not an error in LuaJIT or Krypta. Let me answer you in 3 ways:

## Answer 1 (shortest):

Never use negative integers as an arguments for bit operations and never display the results of bit operations as signed numbers. It leads to seemingly bizarre and sometimes even unpredictable behavior (not only in LuaJIT).

## Answer 2 (longer):

Let's employ a little bit of common logic and binary/hex number knowledge (you should know about negative integers representation to follow me):

All bit operations in LuaJIT (and Krypta) are 32 bit so let's operate in 32 bits. -1844166528 in hex is 0x92144080. 0x92144080 shifted 8 bits to the right is obviously 0x00921440 (8 bits = 2 hex digits). The 32 bit hex number 0x00921440 is **obviously positive**. In fact, any hex number binary-shifted any number of bits to the right must be positive, because its first bit will be always zero. So it seems that LuaJIT is absolutely correct and all other languages are wrong. Right? Well, it's complicated...

## Answer 3 (longest):

Why do all the other languages show the "wrong" answer?

In Javascript, you used the ">>" operator, which is "Sign-propagating right-shift". That's wrong. LuaJIT's bit.rshift() corresponds to Javascript's ">>>" ("Zero-fill right shift").

### Javascript:
```
console.log(-1844166528 >>> 8)
9573440 // The same as in Lua!
```

In Go and Rust, according to what I found online (I don't use them), ">>" is a logical shift on unsigned values and **an arithmetic (sign-propagating) shift on signed values**. So if you use it on a negative value, it automatically operates as ">>" in Javascript, which you do not want.

## Conclusion

Reiterating the first answer: If you use bit operations on n-bit integers, you should never ever use signed integers. Or, in other words, never ever print the results of bit operations as signed integers (unfortunately, LuaJIT's default type is signed integer). If you do, you might even get differents results on different platforms using the same language! Read this: http://bitop.luajit.org/api.html#tobit and this: http://bitop.luajit.org/semantics.html 

The number you write as -1844166528 should be always displayed and written as 0x92144080. See here:

### LuaJIT
```
num = bit.tobit(-1844166528)
print(bit.tohex(num))
92144080
print(bit.tohex(bit.rshift(num, 8)))
00921440 //Exactly as it should be
```

Also, to correctly convert LuaJIT algorithms to other languages, you must be sure that all bit operations happen  in 32 bits, not in 64! I cannot tell you in detail how to do that but I can imagine that in some of those languages, under some circumstances, 0xFFFFFFFF shifted 1 bit to the left would be 0x1FFFFFFFE. That's wrong! It must be 0xFFFFFFFE because in LuaJIT, all those algorithms operate in 32 bits only.

I hope that explains everything.

**Comment by burningtree** [comment]
Thanks for your quick and comprehensive explanation. I never play with bit coding, its new for me, so now I understand that there are two kinds of right-shift (logical and arithmetic - `bit.rshift` use logical) and how it works.

So, for my Go implementation of krypta, I will use this workaround, which returns logical shift even for negative integers (works well):
```go
func lrshift32(n int32, shft uint32) int32 {
    maxnum := int32(^uint32(0) >> 1)
    return (n >> shft) & (maxnum >> (shft - 1))
}
```
Live demo: https://play.golang.org/p/7nEIYlSlrFx

**Comment by fuxoft** [comment]
That probably works but it's brutally over-complicated. You don't need a special function, you just need to correctly define the types. I have tried it in play.golang.org and this seems to work perfectly in Go:

```
n := uint32(0x92144080)
fmt.Println(n >> 8)
```
Or, better yet:
```
func main() {
	n := uint32(0x92144080)
	fmt.Printf("%#x", n >> 8) // hex is better!
}
```

As I tried to explain before, having signed numbers anywhere when doing bit operations is probably a sign (LOL :smile:) that you are doing something wrong.
