### ISSUE TITLE
Go implementation (go-krypta)

### ISSUE THREAD

**Issue by burningtree** [fuxoft/krypta#3]
Hello again, František,

As I said before, I'm working on the implementation of *krypta* in Go language and I want to share some thoughts about it.

These are my motivations:

- **I want to learn Go & Lua** - study project
- **I like *krypta*** - it's exactly what I was looking for own use, I like its simplicity
- **There is currently only one implementation** (this reference) - I believe that for every security tool like this is better to have at least two working implementations in different languages
- **Faster processing** - Lua is fast, but not fast enough - faster processing means that you can calculate bigger `DIFFICULTY` at the same time (greater safety)

I worked a lot in the last few days and now I have finally finished first working version (currently without Bitcoin address generation and QR codes, but generated `masterseed` and pwds are the same, so the main logic is complete):

https://github.com/burningtree/go-krypta

My plan is to re-implement all functionality and later to come up with some improvements (which of course I will push back as Pull request here). I would like to keep my implementation 100% compatible.

I would like to ask @fuxoft:

1. What are your future plans with _krypta_?
2. What about to make it more user-friendly?  (I mean for non-programmers). 
For example, expand documentation with parts about installation, create a simple static webpage for better promotion or maybe create a GUI (even minimal Linux distributions have X11).

**Comment by burningtree** [comment]
I have first results from `calibrate()`, and it looks like it runs roughly 6-7x times faster.
On `MAXDIFC` (31)  its speedup from 10 years to 555 days.

EDIT: Keep in mind that these results are only 1 core - my next challenge will be probably to try to make it work concurrently using `goroutines` and `runtime.GOMAXPROCS()`.

### LuaJIT
```
CALIBRATION RESULTS FOR THIS MACHINE:
Difficulty 6 takes approx. 10 seconds.
Difficulty 7 takes approx. 20 seconds.
Difficulty 8 takes approx. 40 seconds.
Difficulty 9 takes approx. 80 seconds.
...
Difficulty 28 takes approx. 485 days.
Difficulty 29 takes approx. 970 days.
Difficulty 30 takes approx. 5 years.
Difficulty 31 takes approx. 10 years.
```

### Go
```
CALIBRATION RESULTS FOR THIS MACHINE:
Difficulty 9 takes approx. 11.44 seconds
Difficulty 10 takes approx. 22.88 seconds
Difficulty 11 takes approx. 45.75 seconds
Difficulty 12 takes approx. 91.51 seconds
...
Difficulty 28 takes approx. 69.41 days
Difficulty 29 takes approx. 138.82 days
Difficulty 30 takes approx. 277.63 days
Difficulty 31 takes approx. 555.27 days
```

Machine: 2.3Ghz Core i5 (2core), 8GB RAM, MacOS 10.13

**Comment by fuxoft** [comment]
> What are your future plans with krypta?

Primarily, I use it to safeguard my long time Bitcoin wallets because this seems (to me specifically) like better solution than the others on offer

> What about to make it more user-friendly? (I mean for non-programmers). For example, expand documentation with parts about installation, create a simple static webpage for better promotion or maybe create a GUI (even minimal Linux distributions have X11).

II don't think that's necessary. Krypta is meant for people who use CLI and are OK with it. Krypta exists primarily for me but I thought that someone, somewhere, might also find it useful. Also, GitHub serves as an online safety backup of sorts, so that I can use Krypta form almost anywhere. Krypta is designed to run without installation, on computers without graphical environment (see the README.md). If someone wants, he can of course fork Krypta and improve it. In fact, someone has already done so.

**Comment by fuxoft** [comment]
> Keep in mind that these results are only 1 core - my next challenge will be probably to try to make it work concurrently using goroutines and runtime.GOMAXPROCS().

Krypta is specifically designed to be immune to attempts at concurrency (because getting access to more CPU cores is easier that getting access to faster CPUs). If my Difficulty takes 10 seconds on my PC, I don't want average PCs in 3 years to take just 1 second to crack the same Difficulty. If you find a way that makes Krypta's Master Key generation significantly faster on multiple cores, that basically means my design has failed. :smile:
